### ISSUE TITLE
about attention map

### ISSUE THREAD

**Issue by amiltonwong** [umyta/A-SCN#1]
Hi, @umyta ,

Thanks for releasing your package. I'm interested in how to make [Fig.6](https://www.dropbox.com/s/i035yqckt0t58kj/Fig.6.jpg?dl=0) and [Fig.7](https://www.dropbox.com/s/fla8l1isliw2qme/Fig.7.jpg?dl=0) in your paper. Could you release the corresponding code? Or could you list the main steps or hints on how to capture and visualize the attention weights?

THX!

**Comment by umyta** [comment]
Hi @amiltonwong , thanks for your interest! If I remember this correctly, you can save these [weights](https://github.com/umyta/A-SCN/blob/master/models/ascn_cls.py#L89) and visualize the value of each corresponding point against the rest in terms of a color range for both figures. It is possible that you may not learn exactly the same set of weights, hence your image may not be exactly the same as what is in the paper. Hope this helps.
